# Generated by Django 3.2.3 on 2022-02-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='todouser',
            name='birthday_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
